version: '3'

services:
  mongo_app:
    container_name: mongo_app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8081:8081
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/proyectou2mongo
    depends_on:
      - mongo_db
    networks:
      - my_custom_network
    volumes:
      - mongo_app_data:/app/data

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - 27020:27017
    networks:
      - my_custom_network
    volumes:
      - mongo_data:/data/db

networks:
  my_custom_network:
    driver: bridge

volumes:
  mongo_app_data:
  mongo_data:
